Firecert 2639
rdkcentral/firebolt-certification-suite pull request #300
Opened 2024-12-23 20:04 UTC by kdivya153

2024-12-23 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/firebolt-certification-suite?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/firebolt-certification-suite?pullRequest=300) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: kdivya153<br/>:x: jbigel<br/>:x: semantic-release-bot<br/><hr/>**jbigel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/firebolt-certification-suite?pullRequest=300) it.</sub>

2025-01-13 18:21 UTC, kschrief requested changes

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setDiscoveryPolicy("Allow");```
Are the only options "Allow" and (I'm assuming) "Disallow"? If so can we put them here as the two options?

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setLifecycleState("background");```
Can we link to the possible lifecycle states?

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setLocale("en-US");``` seeks to set the Locale to "true"
The code and the description for this example do not match

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +<summary><b>fcsSetters.setPreferredAudioLanguagese</b></summary>
This appears to be a typo for "setPreferredAudioLanguages"

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +function setVoiceGuidance(attribute, value) {
You only have enabling and disabling VG in here. Can't this set other things like speed, voice, etc?

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setAdditionalInfo("{ key: 'exampleKey', value: 'exampleValue' }");```
Is there somewhere where we can get all the available metadata options? Or can the metadata just be anything?

2025-01-13 18:21 UTC, kschrief commented on defaultModule/requestModules/fcsSetters.md
> +function setAudioDescriptionSettings(attribute, value) {
Are there other options besides just enabling or disabling?

2025-01-14 15:40 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +function setAudioDescriptionSettings(attribute, value) {
IIn the excel sheet,I see the comment saying it has to return true/false so only setEnabled function is neeeded.So I dont think we are supporting any other options other than enable/disable.

In excel : "Returns only true/false & hence only setEnabled function is needed"

2025-01-14 15:50 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setDeviceAudio("Stereo");```
Addressed

2025-01-14 16:27 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setLifecycleState("background");```
Addressed

2025-01-14 16:30 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +Param **value** will represents the desired language.
We do have separate method for setting Locale.So do we still need to mention the value is passed as locale?

As per excel sheet
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/4754aca8-cdcb-433b-996d-a5859995779a" />

2025-01-14 16:34 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +<summary><b>fcsSetters.setPreferredAudioLanguagese</b></summary>
Addressed

2025-01-14 16:36 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +function setVoiceGuidance(attribute, value) {
As per excel sheet,Voice guidance will havee only setEnable() as global API
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/ae8b8a73-8e8f-41e8-a72f-f587de68d413" />

2025-01-14 16:40 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +Param **value** will contain the appId to launch on the DUT.
Addressed

2025-01-14 17:12 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setDeviceHdcp("{"hdcp2.2": true}")```
Addressed

2025-01-14 17:13 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setDeviceHdr("{"dolbyVision": true}")```
Addressed

2025-01-14 17:13 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setDeviceNetwork("{"state": "connected", "type": "wifi"}")```
Addressed

2025-01-14 18:41 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setAdditionalInfo("{ key: 'exampleKey', value: 'exampleValue' }");```
Metadata can be anything,just double checked with Joe and it can be anything

2025-01-23 15:36 UTC, kdivya153 commented on defaultModule/requestModules/fcsSetters.md
> +```fcsSetters.setCountryCode("US")```
Addressed

2025-01-27 16:36 UTC, kschrief approved these changes

2025-01-28 15:10 UTC, merged

2025-01-28 15:11 UTC, jbigel commented
:tada: This PR is included in version 1.7.0-dev.4 :tada:

The release is available on [GitHub release](https://github.com/rdkcentral/firebolt-certification-suite/releases/tag/v1.7.0-dev.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: